export enum MessageType {
    PING = 'PING',
    PONG = 'PONG',
    CREATE_SESSION = 'CREATE_SESSION',
    SESSION_CREATED = 'SESSION_CREATED',
    JOIN_SESSION = 'JOIN_SESSION',
    SESSION_JOINED = 'SESSION_JOINED',
    LEAVE_SESSION = 'LEAVE_SESSION',
    SESSION_LEFT = 'SESSION_LEFT',
    REQUEST_WORKSPACE_SNAPSHOT = 'REQUEST_WORKSPACE_SNAPSHOT',
    WORKSPACE_SNAPSHOT = 'WORKSPACE_SNAPSHOT',
    FILE_CREATED = 'FILE_CREATED',
    FILE_CHANGED = 'FILE_CHANGED',
    FILE_DELETED = 'FILE_DELETED',
    ERROR = 'ERROR'
}
